version: '3.8'
services:
  service-discovery:
    container_name: 'service-discovery'
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - 8761
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://service-discovery:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - helpdesk
  
  config-server:
    container_name: 'config-server'
    build:
      context: ./config-server
      dockerfile: Dockerfile
    environment:
      - CONFIG_SERVER_URI=https://github.com/jonvitor/help-desk-configs
      - CONFIG_SERVER_USERNAME=jonvitor
      - CONFIG_SERVER_PASSWORD=
      - EUREKA_SERVER_URI=http://service-discovery:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - helpdesk

 # auth-service-api:
 #   container_name: 'auth-service-api'
 #   build:
 #     context: ./auth-service-api
 #     dockerfile: Dockerfile
 #   environment:
 #     - SPRING_PROFILES_ACTIVE=dev
 #     - EUREKA_SERVER_URI=http://service-discovery:8761/eureka
 #     - CONFIG_SERVER_URI=http://config-server:8888
 #   depends_on:
 #     service-discovery:
 #       condition: service_healthy
 #     config-server:
 #       condition: service_healthy
 #   networks:
 #     - helpdesk
 #
 # user-service-api:
 #   container_name: 'user-service-api'
 #   build:
 #     context: ./user-service-api
 #     dockerfile: Dockerfile
 #   environment:
 #     - SPRING_PROFILES_ACTIVE=dev
 #     - EUREKA_SERVER_URI=http://service-discovery:8761/eureka
 #     - CONFIG_SERVER_URI=http://config-server:8888
 #   depends_on:
 #     config-server:
 #       condition: service_healthy
 #     service-discovery:
 #       condition: service_healthy
 #   networks:
 #     - helpdesk
 #
 # order-service-api:
 #   container_name: 'order-service-api'
 #   build:
 #     context: ./order-service-api
 #     dockerfile: Dockerfile
 #   environment:
 #     - SPRING_PROFILES_ACTIVE=dev
 #     - EUREKA_SERVER_URI=http://service-discovery:8761/eureka
 #     - CONFIG_SERVER_URI=http://config-server:8888
 #   depends_on:
 #     config-server:
 #       condition: service_healthy
 #     service-discovery:
 #       condition: service_healthy
 #   networks:
 #     - helpdesk
networks:
  helpdesk:
    driver: bridge