spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: 'user-service-api'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}