spring:
  application:
    name: 'order-service-api'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}