spring:
  application:
    name: 'order-service-api'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 10000