spring:
    application:
        name: 'config-server'
    cloud:
        config:
          server:
            git:
              uri: ${CONFIG_SERVER_URI}
              default-label: main
              username: ${CONFIG_SERVER_USERNAME}
              password: ${CONFIG_SERVER_PASSWORD}
eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_SERVER_URI}

server:
    port: ${PORT:8888}